openapi: 3.0.0
info:
  version: '1.0'
  title: 'bmi calculator'
  description: 'A knowledge object to calculate bmi and categories.'
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /endpoints/bmi/calculator/v1.0
    description: Calculate bmi
tags:
  - name: KO Endpoints
    description: bmi calculation Endpoints    
paths:
  /bmi:
    post:
      summary: Calculate bmi value.
      description: Calculates bmi value.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:  
                height:
                  type: number
                  format: float
                  description: Height of the person. If using 'imperial' unit_system, use height in inches.
                  example: 175.0              
                weight:
                  type: number
                  format: float
                  description: Weight of the person. If using 'imperial' unit_system, use weight in pounds.
                  example: 70.0                
                unit_system:
                  type: string
                  enum: [metric, imperial]
                  description: Unit system for weight and height ('metric' or 'imperial').
                  example: metric
      responses:
        '200':
          description: Successfully calculated bmi value.
          content:
            application/json:
              schema:
                type: object
                properties:
                  bmi:
                    type: number
                    format: float
                    description: bmi.
                    example: 19.0
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
  /category:
    post:
      summary: Calculate category value.
      description: Calculates category value.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:  
                bmi:
                  type: number
                  format: float
                  description: bmi of the person. 
                  example: 20.0              
      responses:
        '200':
          description: Successfully calculated bmi category.
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: string
                    description: bmi category.
                    example: Normal weight
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'